/// @description variáveis
estado = "normal";
contador = 0;
vida_max = 20;
vida_atual = 20;
redutor = 0.025;
aumentar = false;
diminuir = false;
imunidade = false;
cor_mstate = "normal"
global.planetavivo = true;
global.colisoes = 0;